/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul7_2;

import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class Frame4 extends javax.swing.JFrame {

    /**
     * Creates new form Frame4
     */
    public Frame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new java.awt.Panel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        Tinggi = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        Panjang = new javax.swing.JTextField();
        panel2 = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        Rusuk = new javax.swing.JTextField();
        OK1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Jari = new javax.swing.JTextField();
        OK2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Program Penghitung Volume Bangung Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, -10, 310, 60);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        panel1.setLayout(null);

        jLabel13.setText("Masukkan Panjang : ");
        panel1.add(jLabel13);
        jLabel13.setBounds(20, 20, 130, 30);

        jLabel14.setText("Masukkan Lebar : ");
        panel1.add(jLabel14);
        jLabel14.setBounds(20, 60, 130, 30);

        jPanel1.setLayout(null);

        jLabel15.setText("Masukkan Tinggi : ");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 110, 130, 30);

        jLabel2.setText("cm");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 110, 40, 30);

        jLabel3.setText("cm");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 30, 40, 30);

        jLabel4.setText("cm");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 70, 40, 30);

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        jPanel1.add(OK);
        OK.setBounds(150, 180, 80, 30);
        jPanel1.add(Tinggi);
        Tinggi.setBounds(140, 110, 130, 30);
        jPanel1.add(Lebar);
        Lebar.setBounds(140, 70, 130, 30);
        jPanel1.add(Panjang);
        Panjang.setBounds(140, 30, 130, 30);

        panel1.add(jPanel1);
        jPanel1.setBounds(-10, -10, 410, 260);

        jTabbedPane1.addTab("Balok", panel1);

        panel2.setLayout(null);

        jPanel2.setLayout(null);
        jPanel2.add(Rusuk);
        Rusuk.setBounds(90, 30, 130, 30);

        OK1.setText("OK");
        OK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK1ActionPerformed(evt);
            }
        });
        jPanel2.add(OK1);
        OK1.setBounds(150, 130, 80, 30);

        jLabel6.setText("Rusuk :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 30, 70, 30);

        panel2.add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 250);

        jTabbedPane1.addTab("Kubus", panel2);

        panel3.setLayout(null);

        jLabel7.setText("Jari-jari :");
        panel3.add(jLabel7);
        jLabel7.setBounds(20, 20, 70, 30);

        jPanel3.setLayout(null);
        jPanel3.add(Jari);
        Jari.setBounds(90, 20, 130, 30);

        OK2.setText("OK");
        OK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK2ActionPerformed(evt);
            }
        });
        jPanel3.add(OK2);
        OK2.setBounds(140, 130, 80, 30);

        panel3.add(jPanel3);
        jPanel3.setBounds(0, 0, 410, 260);

        jTabbedPane1.addTab("Bola", panel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 30, 400, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(Panjang.getText());
        lebar = Integer.parseInt(Lebar.getText());
        tinggi = Integer.parseInt(Tinggi.getText());
        
        int hasil = panjang*lebar*tinggi;
        
        try{
            
            JOptionPane.showMessageDialog(null,"Volume Balok adalah : "+hasil,"Volume",
                    JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
        
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
            
        }
        
    }//GEN-LAST:event_OKActionPerformed

    private void OK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK1ActionPerformed
        // TODO add your handling code here:
        
        int sisi;
        sisi = Integer.parseInt(Rusuk.getText());
        int hasil = sisi*sisi*sisi;
        
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus adalah : "
            +hasil,"Volume",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_OK1ActionPerformed

    private void OK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK2ActionPerformed
        // TODO add your handling code here:
        
        float jari;
        jari = Integer.parseInt(Jari.getText());
        float hasil = (float) (4/3*Math.PI*jari*jari*jari);
        
        try {
            JOptionPane.showMessageDialog(null,"Volume Permukaan Bola adalah : "+hasil,
                    "Luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_OK2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jari;
    private javax.swing.JTextField Lebar;
    private javax.swing.JButton OK;
    private javax.swing.JButton OK1;
    private javax.swing.JButton OK2;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Rusuk;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
